# Generated by Django 4.0.7 on 2022-09-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0002_alter_link_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
